server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MyVerySecretKeyForBankingApplication123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Forces the gateway to use IP instead of hostname
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}