server:
  port: 8087

spring:
  application:
    name: document-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

aws:
  s3:
    bucket-name: banking-documents-rsaha
    region: ap-south-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
