server:
  port: 8084

spring:
  application:
    name: payment-service
  # Add this Kafka block to configure the Producer!
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      accountRetry:
        maxAttempts: 3
        waitDuration: 2s
  # Add the Rate Limiter here!
  ratelimiter:
    instances:
      paymentLimiter:
        limitForPeriod: 2        # Extremely low for testing! (2 requests)
        limitRefreshPeriod: 60s  # Per 60 seconds
        timeoutDuration: 0s      # Don't wait, reject immediately